export const INITIAL_PLANTS = [
  {
    id: 1,
    name: 'Alpha Energy Refinery',
    address: '100 Industrial Parkway, Houston, TX 77001',
    timezone: 'America/Chicago',
    status: 'active',
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
    _count: { zones: 3, users: 4, cameras: 6 },
  },
  {
    id: 2,
    name: 'Beta Chemical Hub',
    address: '450 Technology Way, Rotterdam, Netherlands',
    timezone: 'Europe/Amsterdam',
    status: 'active',
    createdAt: '2026-02-01T10:30:00Z',
    updatedAt: '2026-02-01T10:30:00Z',
    _count: { zones: 2, users: 2, cameras: 4 },
  },
  {
    id: 3,
    name: 'Gamma Storage Facility (Maintenance)',
    address: '88 Logistics Blvd, Singapore 629123',
    timezone: 'Asia/Singapore',
    status: 'inactive',
    createdAt: '2026-03-15T14:15:00Z',
    updatedAt: '2026-03-20T09:00:00Z',
    _count: { zones: 2, users: 1, cameras: 2 },
  },
];

export const INITIAL_ZONES = [
  {
    id: 101,
    plant_id: 1,
    name: 'Catalytic Cracking Unit A',
    severity_level: 'critical',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'active',
    createdAt: '2026-01-11T09:00:00Z',
  },
  {
    id: 102,
    plant_id: 1,
    name: 'High Pressure Storage Tank B',
    severity_level: 'high',
    operating_schedule: { start: '06:00', end: '22:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
    status: 'active',
    createdAt: '2026-01-12T11:20:00Z',
  },
  {
    id: 103,
    plant_id: 1,
    name: 'Perimeter Fence & Security Gate',
    severity_level: 'low',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'inactive',
    createdAt: '2026-01-15T15:00:00Z',
  },
  {
    id: 104,
    plant_id: 1,
    name: 'Hydrogen Hydro-treating Unit D',
    severity_level: 'critical',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'active',
    createdAt: '2026-01-18T08:30:00Z',
  },
  {
    id: 105,
    plant_id: 1,
    name: 'Control Room & Dispatch Annex',
    severity_level: 'medium',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'active',
    createdAt: '2026-01-20T14:00:00Z',
  },
  {
    id: 201,
    plant_id: 2,
    name: 'Chemical Synthesis Lab 1',
    severity_level: 'high',
    operating_schedule: { start: '08:00', end: '20:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
    status: 'active',
    createdAt: '2026-02-02T10:00:00Z',
  },
  {
    id: 202,
    plant_id: 2,
    name: 'Hazmat Loading Dock C',
    severity_level: 'medium',
    operating_schedule: { start: '07:00', end: '19:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
    status: 'active',
    createdAt: '2026-02-03T12:30:00Z',
  },
  {
    id: 301,
    plant_id: 3,
    name: 'Cold Storage Vault 10',
    severity_level: 'high',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'inactive',
    createdAt: '2026-03-16T08:00:00Z',
  },
];

export const INITIAL_CAMERAS = [
  {
    id: 501,
    zone_id: 101,
    name: 'CCU Flare Stack Thermal Feed',
    feed_type: 'simulated',
    feed_url_or_path: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 502,
    zone_id: 101,
    name: 'Pressure Control Valve Overlook',
    feed_type: 'rtsp',
    feed_url_or_path: 'rtsp://admin:pass@192.168.1.102:554/stream1',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 503,
    zone_id: 102,
    name: 'Tank B North Perimeter Cam',
    feed_type: 'upload',
    feed_url_or_path: '/feeds/tank_north.mp4',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 504,
    zone_id: 103,
    name: 'Gate 4 License Plate Scanner',
    feed_type: 'rtsp',
    feed_url_or_path: 'rtsp://admin:pass@192.168.1.104:554/stream1',
    status: 'offline',
    is_active: false,
    last_heartbeat_at: '2026-03-28T10:00:00Z',
  },
  {
    id: 507,
    zone_id: 104,
    name: 'Unit D High-Temp Thermal Sensor',
    feed_type: 'simulated',
    feed_url_or_path: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 508,
    zone_id: 105,
    name: 'Control Room Main Access Cam',
    feed_type: 'rtsp',
    feed_url_or_path: 'rtsp://admin:pass@192.168.1.108:554/stream1',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 505,
    zone_id: 201,
    name: 'Lab 1 Fume Hood Safety Cam',
    feed_type: 'simulated',
    feed_url_or_path: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 506,
    zone_id: 301,
    name: 'Vault 10 Temperature Monitor Cam',
    feed_type: 'simulated',
    feed_url_or_path: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    status: 'offline',
    is_active: false,
    last_heartbeat_at: '2026-03-15T12:00:00Z',
  },
];

export const INITIAL_SUPER_ADMIN_ALERTS = [
  {
    id: 'ALT-1001',
    plant_id: 1,
    zone_id: 101,
    zone_name: 'Catalytic Cracking Unit A',
    camera_name: 'CCU Flare Stack Thermal Feed',
    type: 'Hard Hat & Goggles Violation',
    severity: 'high',
    status: 'active',
    timestamp: '10 minutes ago',
    description: 'AI vision detected worker in Sector A without required hard hat and protective eyewear.',
  },
  {
    id: 'ALT-1002',
    plant_id: 1,
    zone_id: 104,
    zone_name: 'Hydrogen Hydro-treating Unit D',
    camera_name: 'Unit D High-Temp Thermal Sensor',
    type: 'Thermal Excursion Threshold Warning',
    severity: 'critical',
    status: 'investigating',
    timestamp: '25 minutes ago',
    description: 'Thermal camera registered surface temp spike (+18°C above baseline) on valve manifold 4B.',
  },
  {
    id: 'ALT-1003',
    plant_id: 1,
    zone_id: 102,
    zone_name: 'High Pressure Storage Tank B',
    camera_name: 'Tank B North Perimeter Cam',
    type: 'Unauthorized Restricted Zone Entry',
    severity: 'medium',
    status: 'active',
    timestamp: '1 hour ago',
    description: 'Motion detector flagged perimeter breach near high-pressure containment vessel.',
  },
  {
    id: 'ALT-1004',
    plant_id: 1,
    zone_id: 105,
    zone_name: 'Control Room & Dispatch Annex',
    camera_name: 'Control Room Main Access Cam',
    type: 'AI Camera Heartbeat Synchronized',
    severity: 'low',
    status: 'resolved',
    timestamp: '3 hours ago',
    description: 'Automated calibration completed for RTSP feed #108. All security telemetry normal.',
  },
  {
    id: 'ALT-2001',
    plant_id: 2,
    zone_id: 201,
    zone_name: 'Chemical Synthesis Lab 1',
    camera_name: 'Lab 1 Fume Hood Safety Cam',
    type: 'Chemical Spill Hazard Detected',
    severity: 'high',
    status: 'active',
    timestamp: '15 minutes ago',
    description: 'Optical liquid analysis flagged liquid pool near Fume Hood station #2.',
  },
];

export const INITIAL_SUPER_ADMIN_METRICS = {
  ppeComplianceRate: 98.4,
  avgResponseTimeMin: 1.2,
  onSitePersonnel: 14,
  activeAlertsCount: 3,
  aiFeedsOnline: 5,
  aiFeedsTotal: 6,
};

export const INITIAL_USERS = [
  {
    id: 1,
    name: 'Eleanor Vance (Super Admin - Plant 1)',
    email: 'superadmin@safeops.io',
    phone: '+1 (555) 100-0001',
    role: 'super_admin',
    plant_id: 1,
    qr_token: 'QR-EMP-1001-ELEANOR',
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date().toISOString(),
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 10,
    name: 'Victor Vance (Super Admin - Plant 2)',
    email: 'superadmin2@safeops.io',
    phone: '+1 (555) 100-0002',
    role: 'super_admin',
    plant_id: 2,
    qr_token: 'QR-EMP-1010-VICTOR',
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date().toISOString(),
    createdAt: '2026-01-02T00:00:00Z',
  },
  {
    id: 11,
    name: 'Unassigned Super Admin',
    email: 'unassigned.sa@safeops.io',
    phone: '+1 (555) 100-0003',
    role: 'super_admin',
    plant_id: null,
    qr_token: 'QR-EMP-1011-UNASSIGNED',
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date().toISOString(),
    createdAt: '2026-01-03T00:00:00Z',
  },
  {
    id: 2,
    name: 'Marcus Brody (Alpha Admin)',
    email: 'marcus.brody@alpha-energy.com',
    phone: '+1 (555) 200-0001',
    role: 'admin',
    plant_id: 1,
    qr_token: 'QR-EMP-1002-MARCUS',
    invited_by: 1,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 3,
    name: 'Sarah Connor (Alpha Manager)',
    email: 'sarah.c@alpha-energy.com',
    phone: '+1 (555) 300-0001',
    role: 'manager',
    plant_id: 1,
    qr_token: 'QR-EMP-1003-SARAH',
    invited_by: 2,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    createdAt: '2026-01-15T14:00:00Z',
  },
  {
    id: 4,
    name: 'Dave Bowman (Alpha Operator)',
    email: 'dave.b@alpha-energy.com',
    phone: '+1 (555) 400-0001',
    role: 'operator',
    plant_id: 1,
    qr_token: 'QR-EMP-1004-DAVE',
    invited_by: 2,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    createdAt: '2026-01-20T09:00:00Z',
  },
  {
    id: 5,
    name: 'Elena Rostova (Beta Admin)',
    email: 'elena.r@beta-chem.com',
    phone: '+1 (555) 500-0001',
    role: 'admin',
    plant_id: 2,
    qr_token: 'QR-EMP-1005-ELENA',
    invited_by: 1,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    createdAt: '2026-02-02T11:00:00Z',
  },
  {
    id: 6,
    name: 'Pending Admin Invitation',
    email: 'new.admin@global-corp.com',
    phone: '+1 (555) 600-0001',
    role: 'admin',
    plant_id: null,
    qr_token: 'QR-EMP-1006-PENDING',
    invited_by: 1,
    invite_status: 'pending',
    account_status: 'active',
    createdAt: '2026-03-25T16:00:00Z',
  },
  {
    id: 7,
    name: 'Deactivated Worker',
    email: 'old.user@alpha-energy.com',
    phone: '+1 (555) 700-0001',
    role: 'operator',
    plant_id: 1,
    qr_token: 'QR-EMP-1007-DISABLED',
    invited_by: 2,
    invite_status: 'accepted',
    account_status: 'disabled',
    createdAt: '2026-01-05T09:00:00Z',
  },
];

export const INITIAL_ATTENDANCE = [
  {
    id: 10001,
    employee_id: 4,
    employee_name: 'Dave Bowman (Alpha Operator)',
    employee_email: 'dave.b@alpha-energy.com',
    employee_role: 'operator',
    qr_token: 'QR-EMP-1004-DAVE',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    entry_date: new Date().toISOString().split('T')[0],
    entry_timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
    formatted_time: '01:00 PM',
    status: 'Checked-In',
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 10002,
    employee_id: 3,
    employee_name: 'Sarah Connor (Alpha Manager)',
    employee_email: 'sarah.c@alpha-energy.com',
    employee_role: 'manager',
    qr_token: 'QR-EMP-1003-SARAH',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    entry_date: new Date().toISOString().split('T')[0],
    entry_timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
    formatted_time: '12:00 PM',
    status: 'Checked-In',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
];

export const INITIAL_SAFETY_RULES = [
  {
    id: 501,
    name: 'Assembly Line PPE Compliance (Helmet & Vest)',
    description: 'Mandatory hard hat helmet and reflective safety vest in Catalytic Cracking Unit A high hazard zone.',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    zone_id: 101,
    zone_name: 'Catalytic Cracking Unit A',
    camera_id: 1001,
    camera_name: 'CAM-101-NORTH: Cracking Unit Main Platform',
    camera_region_id: 301,
    camera_region_name: 'Cracker Platform Hazard Zone A',
    required_ppe: ['helmet', 'vest'],
    severity: 'high',
    status: 'active',
    frame_sampling_rate: 1,
    min_observations_required: 6,
    total_observation_window: 10,
    min_confidence_threshold: 0.75,
    cooldown_minutes: 5,
    duplicate_detection_window: 300,
    version: 1,
    created_by: 1,
    creator_name: 'Eleanor Vance',
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-03-01T09:00:00Z',
  },
  {
    id: 502,
    name: 'High Pressure Tank Area Full PPE Enforcement',
    description: 'Requires helmet, vest, and safety gloves inside Storage Tank B perimeter during active operations.',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    zone_id: 102,
    zone_name: 'High Pressure Storage Tank B',
    camera_id: 1003,
    camera_name: 'CAM-102-EAST: Storage Tank Pressure Valves',
    camera_region_id: 302,
    camera_region_name: 'Tank Valve Valve Manifold Region',
    required_ppe: ['helmet', 'vest', 'gloves'],
    severity: 'critical',
    status: 'active',
    frame_sampling_rate: 1,
    min_observations_required: 5,
    total_observation_window: 8,
    min_confidence_threshold: 0.80,
    cooldown_minutes: 10,
    duplicate_detection_window: 600,
    version: 1,
    created_by: 2,
    creator_name: 'Marcus Brody',
    createdAt: '2026-03-05T11:30:00Z',
    updatedAt: '2026-03-05T11:30:00Z',
  },
  {
    id: 503,
    name: 'Chemical Synthesis Lab Safety Gear Protocol',
    description: 'Eye goggles, gloves, and lab coat mandatory near synthesis equipment.',
    plant_id: 2,
    plant_name: 'Beta Chemical Hub',
    zone_id: 201,
    zone_name: 'Chemical Synthesis Lab 1',
    camera_id: 2001,
    camera_name: 'CAM-201-MAIN: Synthesis Bench 1',
    camera_region_id: 303,
    camera_region_name: 'Reagent Station Perimeter',
    required_ppe: ['goggles', 'gloves', 'lab_coat'],
    severity: 'medium',
    status: 'active',
    frame_sampling_rate: 2,
    min_observations_required: 4,
    total_observation_window: 8,
    min_confidence_threshold: 0.70,
    cooldown_minutes: 5,
    duplicate_detection_window: 300,
    version: 1,
    created_by: 5,
    creator_name: 'Elena Rostova',
    createdAt: '2026-03-10T14:00:00Z',
    updatedAt: '2026-03-10T14:00:00Z',
  },
];

export const INITIAL_CAMERA_REGIONS = [
  {
    id: 301,
    name: 'Cracker Platform Hazard Zone A',
    description: 'Walkway and elevated maintenance grid surrounding Catalytic Unit A reactor core.',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    zone_id: 101,
    zone_name: 'Catalytic Cracking Unit A',
    camera_id: 1001,
    camera_name: 'CAM-101-NORTH: Cracking Unit Main Platform',
    polygon_points: [
      { x: 0.15, y: 0.20 },
      { x: 0.85, y: 0.20 },
      { x: 0.80, y: 0.85 },
      { x: 0.20, y: 0.85 },
    ],
    original_width: 1280,
    original_height: 720,
    status: 'active',
    created_by: 1,
    creator_name: 'Eleanor Vance',
    createdAt: '2026-03-02T10:00:00Z',
  },
  {
    id: 302,
    name: 'Tank Valve Manifold Region',
    description: 'High-pressure manifold control valve station bounded by safety railing.',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    zone_id: 102,
    zone_name: 'High Pressure Storage Tank B',
    camera_id: 1003,
    camera_name: 'CAM-102-EAST: Storage Tank Pressure Valves',
    polygon_points: [
      { x: 0.25, y: 0.30 },
      { x: 0.75, y: 0.25 },
      { x: 0.90, y: 0.75 },
      { x: 0.10, y: 0.80 },
    ],
    original_width: 1280,
    original_height: 720,
    status: 'active',
    created_by: 2,
    creator_name: 'Marcus Brody',
    createdAt: '2026-03-06T12:00:00Z',
  },
  {
    id: 303,
    name: 'Reagent Station Perimeter',
    description: 'Fume hood intake and chemical dispenser bench area.',
    plant_id: 2,
    plant_name: 'Beta Chemical Hub',
    zone_id: 201,
    zone_name: 'Chemical Synthesis Lab 1',
    camera_id: 2001,
    camera_name: 'CAM-201-MAIN: Synthesis Bench 1',
    polygon_points: [
      { x: 0.30, y: 0.15 },
      { x: 0.70, y: 0.15 },
      { x: 0.75, y: 0.70 },
      { x: 0.25, y: 0.70 },
    ],
    original_width: 1280,
    original_height: 720,
    status: 'active',
    created_by: 5,
    creator_name: 'Elena Rostova',
    createdAt: '2026-03-11T15:00:00Z',
  },
];

export const INITIAL_CCTV_VIDEOS = [
  {
    id: 701,
    filename: 'cctv_refinery_unit_a_shift2.mp4',
    original_name: 'cctv_refinery_unit_a_shift2.mp4',
    storage_path: '/uploads/videos/cctv_refinery_unit_a_shift2.mp4',
    file_size: 24500000,
    duration_seconds: 45.0,
    width: 1280,
    height: 720,
    fps: 30.0,
    mime_type: 'video/mp4',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    zone_id: 101,
    zone_name: 'Catalytic Cracking Unit A',
    camera_id: 1001,
    camera_name: 'CAM-101-NORTH: Cracking Unit Main Platform',
    uploader_id: 2,
    uploader_name: 'Marcus Brody',
    upload_timestamp: '2026-04-01T10:00:00Z',
    processing_status: 'completed',
  },
  {
    id: 702,
    filename: 'cctv_storage_tank_b_inspection.mp4',
    original_name: 'cctv_storage_tank_b_inspection.mp4',
    storage_path: '/uploads/videos/cctv_storage_tank_b_inspection.mp4',
    file_size: 18200000,
    duration_seconds: 30.0,
    width: 1280,
    height: 720,
    fps: 30.0,
    mime_type: 'video/mp4',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    zone_id: 102,
    zone_name: 'High Pressure Storage Tank B',
    camera_id: 1003,
    camera_name: 'CAM-102-EAST: Storage Tank Pressure Valves',
    uploader_id: 2,
    uploader_name: 'Marcus Brody',
    upload_timestamp: '2026-04-02T14:30:00Z',
    processing_status: 'unprocessed',
  },
];

export const INITIAL_VIDEO_JOBS = [
  {
    id: 801,
    job_uuid: 'JOB-20260401-1001',
    video_id: 701,
    video_name: 'cctv_refinery_unit_a_shift2.mp4',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    camera_id: 1001,
    camera_name: 'CAM-101-NORTH: Cracking Unit Main Platform',
    region_id: 301,
    region_name: 'Cracker Platform Hazard Zone A',
    status: 'completed',
    progress_percentage: 100,
    current_frame: 150,
    total_frames: 150,
    rule_snapshot: {
      id: 501,
      name: 'Assembly Line PPE Compliance (Helmet & Vest)',
      required_ppe: ['helmet', 'vest'],
      min_observations_required: 6,
      total_observation_window: 10,
      min_confidence_threshold: 0.75,
      cooldown_minutes: 5,
    },
    region_snapshot: {
      id: 301,
      name: 'Cracker Platform Hazard Zone A',
      polygon_points: [
        { x: 0.15, y: 0.20 },
        { x: 0.85, y: 0.20 },
        { x: 0.80, y: 0.85 },
        { x: 0.20, y: 0.85 },
      ],
    },
    summary_results: {
      total_observations: 10,
      confirmed_violations: 1,
      rejected_candidates: 2,
    },
    started_at: '2026-04-01T10:01:00Z',
    completed_at: '2026-04-01T10:02:15Z',
  },
];

export const INITIAL_DETECTION_EVENTS = [
  {
    id: 901,
    job_id: 801,
    rule_id: 501,
    rule_name: 'Assembly Line PPE Compliance (Helmet & Vest)',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    camera_id: 1001,
    camera_name: 'CAM-101-NORTH: Cracking Unit Main Platform',
    region_id: 301,
    region_name: 'Cracker Platform Hazard Zone A',
    timestamp_seconds: 12.4,
    frame_index: 42,
    violation_category: 'Missing Helmet & Vest',
    detected_ppe: [],
    missing_ppe: ['helmet', 'vest'],
    confidence: 0.94,
    bounding_box: { x1: 0.35, y1: 0.30, x2: 0.55, y2: 0.75 },
    in_region: true,
    verification_status: 'confirmed',
    verification_reason: 'Persistent violation confirmed: 7 of 10 consecutive frame observations detected missing helmet & vest inside camera region.',
    incident_id: 9001,
    created_at: '2026-04-01T10:01:45Z',
  },
  {
    id: 902,
    job_id: 801,
    rule_id: 501,
    rule_name: 'Assembly Line PPE Compliance (Helmet & Vest)',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    camera_id: 1001,
    camera_name: 'CAM-101-NORTH: Cracking Unit Main Platform',
    region_id: 301,
    region_name: 'Cracker Platform Hazard Zone A',
    timestamp_seconds: 24.8,
    frame_index: 84,
    violation_category: 'Missing Gloves',
    detected_ppe: ['helmet', 'vest'],
    missing_ppe: ['gloves'],
    confidence: 0.62,
    bounding_box: { x1: 0.60, y1: 0.25, x2: 0.78, y2: 0.65 },
    in_region: true,
    verification_status: 'rejected',
    verification_reason: 'Confidence 0.62 below minimum threshold 0.75 and observations (2/10) failed persistence requirement.',
    incident_id: null,
    created_at: '2026-04-01T10:02:00Z',
  },
];

export const INITIAL_INCIDENTS = [
  {
    id: 9001,
    incident_uuid: 'INC-20260401-9001',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    zone_id: 101,
    zone_name: 'Catalytic Cracking Unit A',
    camera_id: 1001,
    camera_name: 'CAM-101-NORTH: Cracking Unit Main Platform',
    camera_region_id: 301,
    camera_region_name: 'Cracker Platform Hazard Zone A',
    job_id: 801,
    detection_event_id: 901,
    violation_category: 'Missing Helmet & Vest',
    severity: 'high',
    first_observed_timestamp: '00:00:12',
    last_observed_timestamp: '00:00:18',
    creation_timestamp: '2026-04-01T10:01:45Z',
    confidence_score: 0.94,
    verification_summary: 'Confirmed persistent violation: 7/10 sampled frames verified inside Cracker Platform Hazard Zone A.',
    status: 'open',
    assigned_operator_id: 4,
    assigned_operator_name: 'Dave Bowman (Alpha Operator)',
    evidence_url: '/uploads/videos/cctv_refinery_unit_a_shift2.mp4#t=12',
    notes: 'Automated AI detection logged missing hard hat and safety vest.',
    createdAt: '2026-04-01T10:01:45Z',
  },
];


