export const INITIAL_PLANTS = [
  {
    id: 1,
    name: 'Alpha Energy Refinery',
    address: '100 Industrial Parkway, Houston, TX 77001',
    timezone: 'America/Chicago',
    status: 'active',
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
    _count: { zones: 3, users: 4, cameras: 6 },
  },
  {
    id: 2,
    name: 'Beta Chemical Hub',
    address: '450 Technology Way, Rotterdam, Netherlands',
    timezone: 'Europe/Amsterdam',
    status: 'active',
    createdAt: '2026-02-01T10:30:00Z',
    updatedAt: '2026-02-01T10:30:00Z',
    _count: { zones: 2, users: 2, cameras: 4 },
  },
  {
    id: 3,
    name: 'Gamma Storage Facility (Maintenance)',
    address: '88 Logistics Blvd, Singapore 629123',
    timezone: 'Asia/Singapore',
    status: 'inactive',
    createdAt: '2026-03-15T14:15:00Z',
    updatedAt: '2026-03-20T09:00:00Z',
    _count: { zones: 2, users: 1, cameras: 2 },
  },
];

export const INITIAL_ZONES = [
  {
    id: 101,
    plant_id: 1,
    name: 'Catalytic Cracking Unit A',
    severity_level: 'critical',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'active',
    createdAt: '2026-01-11T09:00:00Z',
  },
  {
    id: 102,
    plant_id: 1,
    name: 'High Pressure Storage Tank B',
    severity_level: 'high',
    operating_schedule: { start: '06:00', end: '22:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
    status: 'active',
    createdAt: '2026-01-12T11:20:00Z',
  },
  {
    id: 103,
    plant_id: 1,
    name: 'Perimeter Fence & Security Gate',
    severity_level: 'low',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'inactive',
    createdAt: '2026-01-15T15:00:00Z',
  },
  {
    id: 104,
    plant_id: 1,
    name: 'Hydrogen Hydro-treating Unit D',
    severity_level: 'critical',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'active',
    createdAt: '2026-01-18T08:30:00Z',
  },
  {
    id: 105,
    plant_id: 1,
    name: 'Control Room & Dispatch Annex',
    severity_level: 'medium',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'active',
    createdAt: '2026-01-20T14:00:00Z',
  },
  {
    id: 201,
    plant_id: 2,
    name: 'Chemical Synthesis Lab 1',
    severity_level: 'high',
    operating_schedule: { start: '08:00', end: '20:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
    status: 'active',
    createdAt: '2026-02-02T10:00:00Z',
  },
  {
    id: 202,
    plant_id: 2,
    name: 'Hazmat Loading Dock C',
    severity_level: 'medium',
    operating_schedule: { start: '07:00', end: '19:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
    status: 'active',
    createdAt: '2026-02-03T12:30:00Z',
  },
  {
    id: 301,
    plant_id: 3,
    name: 'Cold Storage Vault 10',
    severity_level: 'high',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'inactive',
    createdAt: '2026-03-16T08:00:00Z',
  },
];

export const INITIAL_CAMERAS = [
  {
    id: 501,
    zone_id: 101,
    name: 'CCU Flare Stack Thermal Feed',
    feed_type: 'simulated',
    feed_url_or_path: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 502,
    zone_id: 101,
    name: 'Pressure Control Valve Overlook',
    feed_type: 'rtsp',
    feed_url_or_path: 'rtsp://admin:pass@192.168.1.102:554/stream1',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 503,
    zone_id: 102,
    name: 'Tank B North Perimeter Cam',
    feed_type: 'upload',
    feed_url_or_path: '/feeds/tank_north.mp4',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 504,
    zone_id: 103,
    name: 'Gate 4 License Plate Scanner',
    feed_type: 'rtsp',
    feed_url_or_path: 'rtsp://admin:pass@192.168.1.104:554/stream1',
    status: 'offline',
    is_active: false,
    last_heartbeat_at: '2026-03-28T10:00:00Z',
  },
  {
    id: 507,
    zone_id: 104,
    name: 'Unit D High-Temp Thermal Sensor',
    feed_type: 'simulated',
    feed_url_or_path: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 508,
    zone_id: 105,
    name: 'Control Room Main Access Cam',
    feed_type: 'rtsp',
    feed_url_or_path: 'rtsp://admin:pass@192.168.1.108:554/stream1',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 505,
    zone_id: 201,
    name: 'Lab 1 Fume Hood Safety Cam',
    feed_type: 'simulated',
    feed_url_or_path: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 506,
    zone_id: 301,
    name: 'Vault 10 Temperature Monitor Cam',
    feed_type: 'simulated',
    feed_url_or_path: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    status: 'offline',
    is_active: false,
    last_heartbeat_at: '2026-03-15T12:00:00Z',
  },
];

export const INITIAL_SUPER_ADMIN_ALERTS = [
  {
    id: 'ALT-1001',
    plant_id: 1,
    zone_id: 101,
    zone_name: 'Catalytic Cracking Unit A',
    camera_name: 'CCU Flare Stack Thermal Feed',
    type: 'Hard Hat & Goggles Violation',
    severity: 'high',
    status: 'active',
    timestamp: '10 minutes ago',
    description: 'AI vision detected worker in Sector A without required hard hat and protective eyewear.',
  },
  {
    id: 'ALT-1002',
    plant_id: 1,
    zone_id: 104,
    zone_name: 'Hydrogen Hydro-treating Unit D',
    camera_name: 'Unit D High-Temp Thermal Sensor',
    type: 'Thermal Excursion Threshold Warning',
    severity: 'critical',
    status: 'investigating',
    timestamp: '25 minutes ago',
    description: 'Thermal camera registered surface temp spike (+18°C above baseline) on valve manifold 4B.',
  },
  {
    id: 'ALT-1003',
    plant_id: 1,
    zone_id: 102,
    zone_name: 'High Pressure Storage Tank B',
    camera_name: 'Tank B North Perimeter Cam',
    type: 'Unauthorized Restricted Zone Entry',
    severity: 'medium',
    status: 'active',
    timestamp: '1 hour ago',
    description: 'Motion detector flagged perimeter breach near high-pressure containment vessel.',
  },
  {
    id: 'ALT-1004',
    plant_id: 1,
    zone_id: 105,
    zone_name: 'Control Room & Dispatch Annex',
    camera_name: 'Control Room Main Access Cam',
    type: 'AI Camera Heartbeat Synchronized',
    severity: 'low',
    status: 'resolved',
    timestamp: '3 hours ago',
    description: 'Automated calibration completed for RTSP feed #108. All security telemetry normal.',
  },
  {
    id: 'ALT-2001',
    plant_id: 2,
    zone_id: 201,
    zone_name: 'Chemical Synthesis Lab 1',
    camera_name: 'Lab 1 Fume Hood Safety Cam',
    type: 'Chemical Spill Hazard Detected',
    severity: 'high',
    status: 'active',
    timestamp: '15 minutes ago',
    description: 'Optical liquid analysis flagged liquid pool near Fume Hood station #2.',
  },
];

export const INITIAL_SUPER_ADMIN_METRICS = {
  ppeComplianceRate: 98.4,
  avgResponseTimeMin: 1.2,
  onSitePersonnel: 14,
  activeAlertsCount: 3,
  aiFeedsOnline: 5,
  aiFeedsTotal: 6,
};

export const INITIAL_USERS = [
  {
    id: 1,
    name: 'Eleanor Vance (Super Admin - Plant 1)',
    email: 'superadmin@safeops.io',
    phone: '+1 (555) 100-0001',
    role: 'super_admin',
    plant_id: 1,
    qr_token: 'QR-EMP-1001-ELEANOR',
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date().toISOString(),
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 10,
    name: 'Victor Vance (Super Admin - Plant 2)',
    email: 'superadmin2@safeops.io',
    phone: '+1 (555) 100-0002',
    role: 'super_admin',
    plant_id: 2,
    qr_token: 'QR-EMP-1010-VICTOR',
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date().toISOString(),
    createdAt: '2026-01-02T00:00:00Z',
  },
  {
    id: 11,
    name: 'Unassigned Super Admin',
    email: 'unassigned.sa@safeops.io',
    phone: '+1 (555) 100-0003',
    role: 'super_admin',
    plant_id: null,
    qr_token: 'QR-EMP-1011-UNASSIGNED',
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date().toISOString(),
    createdAt: '2026-01-03T00:00:00Z',
  },
  {
    id: 2,
    name: 'Marcus Brody (Alpha Admin)',
    email: 'marcus.brody@alpha-energy.com',
    phone: '+1 (555) 200-0001',
    role: 'admin',
    plant_id: 1,
    qr_token: 'QR-EMP-1002-MARCUS',
    invited_by: 1,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 3,
    name: 'Sarah Connor (Alpha Manager)',
    email: 'sarah.c@alpha-energy.com',
    phone: '+1 (555) 300-0001',
    role: 'manager',
    plant_id: 1,
    qr_token: 'QR-EMP-1003-SARAH',
    invited_by: 2,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    createdAt: '2026-01-15T14:00:00Z',
  },
  {
    id: 4,
    name: 'Dave Bowman (Alpha Operator)',
    email: 'dave.b@alpha-energy.com',
    phone: '+1 (555) 400-0001',
    role: 'operator',
    plant_id: 1,
    qr_token: 'QR-EMP-1004-DAVE',
    invited_by: 2,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    createdAt: '2026-01-20T09:00:00Z',
  },
  {
    id: 5,
    name: 'Elena Rostova (Beta Admin)',
    email: 'elena.r@beta-chem.com',
    phone: '+1 (555) 500-0001',
    role: 'admin',
    plant_id: 2,
    qr_token: 'QR-EMP-1005-ELENA',
    invited_by: 1,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    createdAt: '2026-02-02T11:00:00Z',
  },
  {
    id: 6,
    name: 'Pending Admin Invitation',
    email: 'new.admin@global-corp.com',
    phone: '+1 (555) 600-0001',
    role: 'admin',
    plant_id: null,
    qr_token: 'QR-EMP-1006-PENDING',
    invited_by: 1,
    invite_status: 'pending',
    account_status: 'active',
    createdAt: '2026-03-25T16:00:00Z',
  },
  {
    id: 7,
    name: 'Deactivated Worker',
    email: 'old.user@alpha-energy.com',
    phone: '+1 (555) 700-0001',
    role: 'operator',
    plant_id: 1,
    qr_token: 'QR-EMP-1007-DISABLED',
    invited_by: 2,
    invite_status: 'accepted',
    account_status: 'disabled',
    createdAt: '2026-01-05T09:00:00Z',
  },
];

export const INITIAL_ATTENDANCE = [
  {
    id: 10001,
    employee_id: 4,
    employee_name: 'Dave Bowman (Alpha Operator)',
    employee_email: 'dave.b@alpha-energy.com',
    employee_role: 'operator',
    qr_token: 'QR-EMP-1004-DAVE',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    entry_date: new Date().toISOString().split('T')[0],
    entry_timestamp: new Date(Date.now() - 3600000 * 3).toISOString(),
    formatted_time: '01:00 PM',
    status: 'Checked-In',
    createdAt: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 10002,
    employee_id: 3,
    employee_name: 'Sarah Connor (Alpha Manager)',
    employee_email: 'sarah.c@alpha-energy.com',
    employee_role: 'manager',
    qr_token: 'QR-EMP-1003-SARAH',
    plant_id: 1,
    plant_name: 'Alpha Energy Refinery',
    entry_date: new Date().toISOString().split('T')[0],
    entry_timestamp: new Date(Date.now() - 3600000 * 4).toISOString(),
    formatted_time: '12:00 PM',
    status: 'Checked-In',
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
];

