export const INITIAL_PLANTS = [
  {
    id: 1,
    name: 'Alpha Energy Refinery',
    address: '100 Industrial Parkway, Houston, TX 77001',
    timezone: 'America/Chicago',
    status: 'active',
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-01-10T08:00:00Z',
    _count: { zones: 3, users: 4, cameras: 6 },
  },
  {
    id: 2,
    name: 'Beta Chemical Hub',
    address: '450 Technology Way, Rotterdam, Netherlands',
    timezone: 'Europe/Amsterdam',
    status: 'active',
    createdAt: '2026-02-01T10:30:00Z',
    updatedAt: '2026-02-01T10:30:00Z',
    _count: { zones: 2, users: 2, cameras: 4 },
  },
  {
    id: 3,
    name: 'Gamma Storage Facility (Maintenance)',
    address: '88 Logistics Blvd, Singapore 629123',
    timezone: 'Asia/Singapore',
    status: 'inactive',
    createdAt: '2026-03-15T14:15:00Z',
    updatedAt: '2026-03-20T09:00:00Z',
    _count: { zones: 2, users: 1, cameras: 2 },
  },
];

export const INITIAL_ZONES = [
  {
    id: 101,
    plant_id: 1,
    name: 'Catalytic Cracking Unit A',
    severity_level: 'critical',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'active',
    createdAt: '2026-01-11T09:00:00Z',
  },
  {
    id: 102,
    plant_id: 1,
    name: 'High Pressure Storage Tank B',
    severity_level: 'high',
    operating_schedule: { start: '06:00', end: '22:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
    status: 'active',
    createdAt: '2026-01-12T11:20:00Z',
  },
  {
    id: 103,
    plant_id: 1,
    name: 'Perimeter Fence & Security Gate',
    severity_level: 'low',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'inactive',
    createdAt: '2026-01-15T15:00:00Z',
  },
  {
    id: 201,
    plant_id: 2,
    name: 'Chemical Synthesis Lab 1',
    severity_level: 'high',
    operating_schedule: { start: '08:00', end: '20:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
    status: 'active',
    createdAt: '2026-02-02T10:00:00Z',
  },
  {
    id: 202,
    plant_id: 2,
    name: 'Hazmat Loading Dock C',
    severity_level: 'medium',
    operating_schedule: { start: '07:00', end: '19:00', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'] },
    status: 'active',
    createdAt: '2026-02-03T12:30:00Z',
  },
  {
    id: 301,
    plant_id: 3,
    name: 'Cold Storage Vault 10',
    severity_level: 'high',
    operating_schedule: { start: '00:00', end: '23:59', days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] },
    status: 'inactive',
    createdAt: '2026-03-16T08:00:00Z',
  },
];

export const INITIAL_CAMERAS = [
  {
    id: 501,
    zone_id: 101,
    name: 'CCU Flare Stack Thermal Feed',
    feed_type: 'simulated',
    feed_url_or_path: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 502,
    zone_id: 101,
    name: 'Pressure Control Valve Overlook',
    feed_type: 'rtsp',
    feed_url_or_path: 'rtsp://admin:pass@192.168.1.102:554/stream1',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 503,
    zone_id: 102,
    name: 'Tank B North Perimeter Cam',
    feed_type: 'upload',
    feed_url_or_path: '/feeds/tank_north.mp4',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 504,
    zone_id: 103,
    name: 'Gate 4 License Plate Scanner',
    feed_type: 'rtsp',
    feed_url_or_path: 'rtsp://admin:pass@192.168.1.104:554/stream1',
    status: 'offline',
    is_active: false,
    last_heartbeat_at: '2026-03-28T10:00:00Z',
  },
  {
    id: 505,
    zone_id: 201,
    name: 'Lab 1 Fume Hood Safety Cam',
    feed_type: 'simulated',
    feed_url_or_path: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    is_active: true,
    last_heartbeat_at: new Date().toISOString(),
  },
  {
    id: 506,
    zone_id: 301,
    name: 'Vault 10 Temperature Monitor Cam',
    feed_type: 'simulated',
    feed_url_or_path: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80',
    status: 'offline',
    is_active: false,
    last_heartbeat_at: '2026-03-15T12:00:00Z',
  },
];

export const INITIAL_USERS = [
  {
    id: 1,
    name: 'Eleanor Vance (Super Admin)',
    email: 'superadmin@safeops.io',
    role: 'super_admin',
    plant_id: null,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date().toISOString(),
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 2,
    name: 'Marcus Brody (Alpha Admin)',
    email: 'marcus.brody@alpha-energy.com',
    role: 'admin',
    plant_id: 1,
    invited_by: 1,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 3,
    name: 'Sarah Connor (Alpha Manager)',
    email: 'sarah.c@alpha-energy.com',
    role: 'manager',
    plant_id: 1,
    invited_by: 2,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    createdAt: '2026-01-15T14:00:00Z',
  },
  {
    id: 4,
    name: 'Dave Bowman (Alpha Operator)',
    email: 'dave.b@alpha-energy.com',
    role: 'operator',
    plant_id: 1,
    invited_by: 2,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    createdAt: '2026-01-20T09:00:00Z',
  },
  {
    id: 5,
    name: 'Elena Rostova (Beta Admin)',
    email: 'elena.r@beta-chem.com',
    role: 'admin',
    plant_id: 2,
    invited_by: 1,
    invite_status: 'accepted',
    account_status: 'active',
    last_login_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    createdAt: '2026-02-02T11:00:00Z',
  },
  {
    id: 6,
    name: 'Pending Admin Invitation',
    email: 'new.admin@global-corp.com',
    role: 'admin',
    plant_id: null,
    invited_by: 1,
    invite_status: 'pending',
    account_status: 'active',
    createdAt: '2026-03-25T16:00:00Z',
  },
  {
    id: 7,
    name: 'Deactivated Worker',
    email: 'old.user@alpha-energy.com',
    role: 'operator',
    plant_id: 1,
    invited_by: 2,
    invite_status: 'accepted',
    account_status: 'disabled',
    createdAt: '2026-01-05T09:00:00Z',
  },
];
